### ISSUE TITLE
Availability stored as an array: ["08:00", "16:00"]

### ISSUE THREAD

**Issue by vinceprofeta** [makeplans/makeplans-api#2]
@espen  Hey this looks awesome but just a few questions
1. Is there a reason why you chose to store opening_hours as a single dimensional array and not a two dimensional array? [ ["08:00", "11:00"],  ["01:00", "16:00"]]. I am just trying to get a better understanding of how the system works.
2. Are Slots actually saved as documents/rows on a database table or are they computed when querying for availability based on current bookings and date exceptions?

Thanks, I am possibly looking into using this for a project I am working on, but was curious about the questions above.

**Comment by espen** [comment]
Hey @vinceprofeta.
1. No reason except for poor API planning and a direct result of how we store that information in our database. It seems like we should return a multi dimensional array here but we have no immediate plans for a new version of the API at the moment however I'll look into possibilities of changing this. Thanks for the feedback!
2. Slots are computed at runtime but we do cache them at any level we can as availability can be complex and costly to compute.

I'm gonna go ahead and close this issue now; if you have any more questions feel free to email me: espen@makeplans.net. Would also be interesting to hear what your are planning to build using our API.
