### ISSUE TITLE
api reponse with title: can't be black even though I provided title

### ISSUE THREAD

**Issue by neilnahid** [makeplans/makeplans-api#3]
I'm trying to create a service using api but for some reason it always responds with title:can't be blank
![image](https://user-images.githubusercontent.com/25801890/85508887-8041d800-b627-11ea-9bae-99fff8d69103.png)

**Comment by espen** [comment]
Please see [example](https://github.com/makeplans/makeplans-api#example-request-and-response) on how to set attributes.
